name: StoryRecommender
options:
  bundleIdPrefix: com.wilsonfelicio
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true
settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1"
    INFOPLIST_FILE: StoryRecommender/Info.plist
configs:
  Debug: debug
  Release: release
targets:
  StoryRecommender:
    type: application
    platform: iOS
    sources:
      - path: StoryRecommender
        excludes:
          - "*.xcconfig"
    resources:
      - path: StoryRecommender/Assets.xcassets
      - path: StoryRecommender/Data/curated-stories.json
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.wilsonfelicio.StoryRecommender
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: BS83NN7FM9
      configs:
        Debug:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
    info:
      path: StoryRecommender/Info.plist
      properties:
        CFBundleDisplayName: Story Time
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        ANTHROPIC_API_KEY: $(ANTHROPIC_API_KEY)
    configFiles:
      Debug: Secrets.xcconfig
      Release: Secrets.xcconfig
